### PR TITLE
wacom/live: read Slate dimensions before starting live mode

### PR DESCRIPTION
**Pull request by mont5piques**

### CODE REVIEW

**Review by bentiss — APPROVED** [review]
Looks good.
Tested on a slate A5

**Comment by bentiss** [comment]
Would it be hard to also read the `kete.py` configuration file and use the `Orientation` setting?

**Comment by mont5piques** [comment]
I think it would be more complicated than that. For live mode, we need to read screen orientation instead.
Also, live mode has some issues since generally screen proportions today are 16:9 ~1.777) and paper proportions sqrt(2)~1.4142 whitch cause some distortions of the written text. 
I'm thinking of a mode that adds some margins to compensate this ratio problem.

Ps. : I used live mode to annotate a live powerpoint presentation and it was very cool.

**Comment by whot** [comment]
tbh, this shouldn't be something that kete does. The kernel device we create should be correct in regards to axis resolutions etc. and then all the other stuff needs to be left to the other layers in the stack. Which, in theory, should already handle this case since this isn't the first tablet that has proportions different to the screen. If something doesn't work, that's either a bug in kete of not creating the device correctly, or a bug elsewhere that needs fixing anyway.

**Pull request merged**
