### PR TITLE
Add support for the point size parameter and misc tidyups

### PR DESCRIPTION
**Pull request by whot**
Sorry, too tired to split this up. Motivation was to add the request to fetch the point size, followed by a few tidyups as I was progressing with that.

0xea with 0x14 gives us the point size but for whatever reason this is wrong on the IntuosPro and returns 6 instead of 5. 5 matches the phys dimensions exactly, so not sure what's going on. The spark doesn't have this request, not sure about the slate, please give this a test. Thanks!

### CODE REVIEW

**Comment by bentiss** [comment]
Hey, not sure if this is what you expected:
```shell
11:51:52 DEBUG: tuhi: E0:61:C6:BF:14:4E: UUID 7de6b5eedcce protocol: slate
11:51:52 INFO: tuhi.ble.E0:61:C6:BF:14:4E: Connecting
11:51:52 DEBUG: tuhi: E0:61:C6:BF:14:4E: UUID 7de6b5eedcce protocol: slate
11:51:52 INFO: tuhi.ble.E0:61:C6:BF:14:4E: Connecting
11:51:52 DEBUG: tuhi.ble.E0:61:C6:BF:14:4E: Already connecting
11:51:52 INFO: tuhi.ble.E0:61:C6:BF:14:4E: Connection established
11:51:53 DEBUG: tuhi: E0:61:C6:BF:14:4E: connected for DeviceMode.LISTEN
11:51:54 DEBUG: tuhi.wacom: glamorous sheep is using protocol SLATE
11:51:54 DEBUG: tuhi.wacom: E0:61:C6:BF:14:4E: starting
11:51:54 DEBUG: tuhi.fw: command: check connection
11:51:54 DEBUG: tuhi.fw: E0:61:C6:BF:14:4E: TX NORDIC --> e6 / 06 / 7d e6 b5 ee dc ce
11:51:54 DEBUG: tuhi.fw: E0:61:C6:BF:14:4E: RX NORDIC <-- b3 01 00
11:51:54 DEBUG: tuhi.fw: command: set time
11:51:54 DEBUG: tuhi.fw: E0:61:C6:BF:14:4E: TX NORDIC --> b6 / 06 / 19 08 14 09 51 54
11:51:54 DEBUG: tuhi.fw: E0:61:C6:BF:14:4E: RX NORDIC <-- b3 01 00
11:51:54 DEBUG: tuhi.fw: command: read battery info
11:51:54 DEBUG: tuhi.fw: E0:61:C6:BF:14:4E: TX NORDIC --> b9 / 01 / 00
11:51:54 DEBUG: tuhi.fw: E0:61:C6:BF:14:4E: RX NORDIC <-- ba 02 47 00
11:51:54 INFO: tuhi.wacom: device battery: 71% (discharging)
11:51:54 DEBUG: tuhi.fw: command: get dimensions
11:51:54 DEBUG: tuhi.fw: E0:61:C6:BF:14:4E: TX NORDIC --> ea / 02 / 03 00
11:51:55 DEBUG: tuhi.fw: E0:61:C6:BF:14:4E: RX NORDIC <-- eb 06 03 00 60 54 00 00
11:51:55 DEBUG: tuhi.fw: command: get dimensions
11:51:55 DEBUG: tuhi.fw: E0:61:C6:BF:14:4E: TX NORDIC --> ea / 02 / 04 00
11:51:55 DEBUG: tuhi.fw: E0:61:C6:BF:14:4E: RX NORDIC <-- eb 06 04 00 d0 39 00 00
11:51:55 DEBUG: tuhi.fw: command: get dimensions
11:51:55 DEBUG: tuhi.fw: E0:61:C6:BF:14:4E: TX NORDIC --> ea / 02 / 14 00
11:51:55 DEBUG: tuhi.fw: E0:61:C6:BF:14:4E: RX NORDIC <-- b3 01 01
11:51:55 INFO: tuhi.ble.E0:61:C6:BF:14:4E: Disconnecting
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/btissoir/Src/tuhi/tuhi/wacom.py", line 1237, in _run
    self._wacom_protocol.retrieve_data()
  File "/home/btissoir/Src/tuhi/tuhi/wacom.py", line 1020, in retrieve_data
    self.update_dimensions()
  File "/home/btissoir/Src/tuhi/tuhi/wacom.py", line 722, in update_dimensions
    ps = self.p.execute(Interactions.GET_POINT_SIZE).point_size
  File "/home/btissoir/Src/tuhi/tuhi/protocol.py", line 264, in execute
    return self.get(key, *args, **kwargs).execute()
  File "/home/btissoir/Src/tuhi/tuhi/protocol.py", line 486, in execute
    self._handle_reply(self.reply)
  File "/home/btissoir/Src/tuhi/tuhi/protocol.py", line 914, in _handle_reply
    raise UnexpectedReply(self)
tuhi.protocol.UnexpectedReply: <class 'tuhi.protocol.MsgGetPointSize'>: Interactions.GET_POINT_SIZE - ea / 02 / 14 00 → b3 / 01 / 01

11:51:57 INFO: tuhi.ble.E0:61:C6:BF:14:4E: Disconnected
11:51:57 DEBUG: tuhi: E0:61:C6:BF:14:4E: disconnected
```

**Comment by whot** [comment]
doh. looks like the slate doesn't have that parameter then, we'll need to hardcode it like the spark.

**Comment by whot** [comment]
Ok, updated to only run for the Intuos Pro, on the spark and slate we return a hardcoded 10 with a noop message.

And I've moved all the other patches into separate PRs

**Review by bentiss — APPROVED** [review]
Yep, works for me

I gave a quick review on the individual patches, and I think I am fine with them

**Comment by whot** [comment]
thanks!

**Pull request merged**
