### PR TITLE
Export the battery level/charge status

### PR DESCRIPTION
**Pull request by whot**
Not 100% sure yet if this is the API we want, mostly looking for comments here.

### CODE REVIEW

**Review by bentiss — COMMENTED** [review]
I am not sure what else you can do but this.

The only nitpick is that there is no events emitted on (un)plug of the device, meaning that the battery state we report may not be in sync with the device. It is especially true when restarting tuhi, the battery level is 0 while it should be 'unknown'.

Thinking about it, we should probably have some timeout and report unknown for both if we don't have the battery/charge information in the past 2 min or so.

**Comment by whot** [comment]
looking at upower [1] we should name the charging/discharging bits `BatteryState` with an enum. `BatteryLevel` is used for rough reporting (low, medium, high, boom) and `BatteryPercentage` would be what we're doing.

[1] https://upower.freedesktop.org/docs/Device.html#Device:State

**Comment by whot** [comment]
Updated and force-pushed, now exports `BatteryPercent` and `BatteryState` similar to upower.

**Review by bentiss — APPROVED** [review]
Just checking, do you want to add the timeout in this very same PR or you are fine postponing the timeout to switch the battery to UNKNOWN at a later time?

**Comment by whot** [comment]
some other time, I'll file a bug for that. thanks for the reminder

**Pull request merged**
