### PR TITLE
Merge the TuhiGui into this repo

### LINKED ISSUE #140: Merge TuhiGui into this repository
I've been working on a [tuhigui](http://github.com/whot/tuhigui), which is a GTK GUI for Tuhi.

I think this one should **not** stay a separate project but rather be merged into Tuhi itself, for a number of reasons:
- Tuhi is a DBus server based on the idea that "someone" will write GUIs for each desktop environment. In the last 18 months, no-one was motivated to write *any* GUI, so I very much doubt a proliferation of GUIs will start to exist.
- Tuhi cannot be flatpaked properly because it's not a GUI application. Were TuhiGui a separate app, we'd have to flatpak that one but include Tuhi in it to make sure the server is available.
- Name confusion: I don't want Tuhi to be the server and then have a separate name for the GUI that users will use. It should all just be Tuhi.
- The split between libratbag and piper is a disaster, with packages never matching git and the other way round. I don't want to recreate that here.
- I don't think there's a good argument for shipping Tuhi as its own package anyway. We don't even install `kete` right now. What's the point of a DBus server when there are no tools to actually interact with it out of the box.

### PR DESCRIPTION
**Pull request by whot**
TuhiGui is a project I worked on for the last few days. #140 has an outline but the basic gist is: it's better to make this the official UI than forcing the split between dbus server and UI in an external repo. It's easier for users, it's easier for developers and we can have the one true GUI [1]

This branch merges the (short) history of tuhigui as git subtree, followed by a bunch of fixes to the build system. Hopefully I got everything but the main use-cases work fine. Tuhi itself is largely untouched but for the mainloop change - which wasn't necessary in the end but doesn't hurt.

The split between dbus server and client as separate processes is kept for now, but only on the architecture level. Other than the python files there is no tuhigui, it's all Tuhi now.

To run Tuhi:
```
meson build && ninja -C build && ./build/tuhi.devel
```
Which starts `tuhi-server` and `tuhi-gui` from the development tree. After install, just run `tuhi`. And the flatpak works accordingly too.

[1] given that it's been over 18 months since Tuhi was published first and no independent GUI has materialized, the chances of there being a GUI proliferation is rather slim.

Fixes #140

### CODE REVIEW

**Comment by whot** [comment]
To get the flatpak to work, you'll need to add `"branch": "wip/tuhigui"` to the tuhi `sources` section in the json. Or whatever local branch name you chose.

**Comment by whot** [comment]
Pushed a whole bunch of new commits to style the app into something nice and/or useful. Still needs tweaking but I think this is getting to a decent state.

**Comment by bentiss** [comment]
Just tested this:

The order of the drawings is quite disturbing. First time I run the app, no drawing were shown while the daemon said 8 were loaded. Still, I drew a new one, synced, and everything appeared.
The disturbing ordering is with that the newest is not the first. At that point, I had my drawings sorted the oldest being the first.

But then I killed the app, restarted it, and now I have: June 2019, then August 2019, then July 2019, then February 2018. Which calendar is the app using?

I already mentioned that privately, but the preview widgets are squares, when they should be rectangles -> this affects the proportions of the drawing.

The flatpak is still using the gnome Sdk 3.30. There is a 3.32 available.

`pyxdg` fails at compiling under flatpak from the user, got to use `sudo`

`flatpak run org.freedesktop.Tuhi` failed:
```shell
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
17:15:06 ERROR: tuhi.dbus: Bus not available, is there another Tuhi process running?
Traceback (most recent call last):
  File "/app/libexec/tuhi/tuhi-gui", line 57, in <module>
    gtk_style()
  File "/app/libexec/tuhi/tuhi-gui", line 47, in gtk_style
    Gtk.STYLE_PROVIDER_PRIORITY_APPLICATION
TypeError: Argument 0 does not allow None as a value
```

Killed the session, restarted, and now the bus is still working, but the `TypeError` exception is still happening :/

And to sum up, I am generally OK with the idea and the high level implementation. I haven't had the chance to review individual patches.

**Review by bentiss — APPROVED** [review]
providing ACK

**Comment by whot** [comment]
> Which calendar is the app using?

it was using strftime to sort, but typoed  a `%` so everything expanded into 'Y08' instead of '201908', etc. There is no time-space-continuum conspiracy. Both fixed in the latest push.

> There is a 3.32 available.

Need to test this again, but last time I tried the 3.32 didn't work for me.

> pyxdg fails at compiling under flatpak from the user, got to use sudo

What's your compilation command? I just ran this with `flatpak-builder` and it worked fine. The compilation bit for pyxdg is a `pip3 install` which defaults to the user anyway.

>  while the daemon said 8 were loaded

This may be a bug, not sure if the GUI pulls existing drawings until it connects to the device the first time. Because in the GUI's POV there is no daemon, that's just an implementation detail so you never downloaded drawings without the GUI. This also applies to the failed startup: you're not supposed to have the daemon separate anymore, this is an all-in-one application now.

> but the TypeError exception is still happening :/

The relevant code here, afaict is:
```
    Gtk.StyleContext.add_provider_for_screen(
            Gdk.Screen.get_default(),
            style_provider,
            Gtk.STYLE_PROVIDER_PRIORITY_APPLICATION
            )
```
is `Gdk.Screen.get_default()` returning `None`? Do you have `DISPLAY` or `WAYLAND_DISPLAY` set?

> the preview widgets are squares, 

added to todo list

**Comment by whot** [comment]
>  the preview widgets are squares,

fixed in latest push

**Comment by bentiss** [comment]
> There is no time-space-continuum conspiracy. Both fixed in the latest push.

thanks!

> > pyxdg fails at compiling under flatpak from the user, got to use sudo
>
> What's your compilation command? I just ran this with flatpak-builder and it worked fine. The compilation bit for pyxdg is a pip3 install which defaults to the user anyway.

Weird. I retried today and it was working for pyxdg. The error was related to `bpf` so don't know what was going on. I guess the `flatpack-builder` on the fedora 29 might be slightly out of date.

> >  while the daemon said 8 were loaded
>
> This may be a bug, not sure if the GUI pulls existing drawings until it connects to the device the first time. Because in the GUI's POV there is no daemon, that's just an implementation detail so you never downloaded drawings without the GUI. This also applies to the failed startup: you're not supposed to have the daemon separate anymore, this is an all-in-one application now.

Honestly, not sure this is a major concern. This happens once and then you can forget about it.

> is Gdk.Screen.get_default() returning None? Do you have DISPLAY or WAYLAND_DISPLAY set?

I was using `ssh -Y` and it turns out that running the flatpak on the machine itself is working.

> >    the preview widgets are squares,
>
> fixed in latest push

Great. I guess there is no more strong push back then

**Comment by bentiss** [comment]
Actually, we might want to add a `re-register` button somewhere. I switched from raw install to flatpak, and when switching back to the raw install, the device was asking to be re-paired, without possibility to do it from the UI. This can be extracted as an issue once this gets merged upstream.

**Comment by whot** [comment]
my grand plan for this is to detect that the connection was refused and popping up a re-pairing dialog. No need for a button here.

**Pull request merged**
