### PR TITLE
Add an argument to control the config dir

### PR DESCRIPTION
**Pull request by whot**
Sits on top of #149 

This is useful for testing (`--config-dir=/tmp/$(date)`) but can also be useful when you're debugging Flatpak issues with a non-flatpak run.

### CODE REVIEW

**Comment by whot** [comment]
urgh, tuhigui has a separate item here so this needs to be added there too, planning to merge the GUI first before this one.

**Comment by bentiss** [comment]
LGTM, please rebase and push

**Comment by whot** [comment]
Rebase was easy enough, the fix to tuhigui looks ugly but works. Added as extra patch but will squash before merging - just in case you want to have another look.

**Comment by bentiss** [comment]
Ugly indeed. Go for the merge if you want

**Pull request merged**
